version: '3.3'

services:
  server: 
    build: 
      context: server
      dockerfile: Dockerfile
    ports:
        - '6000:6000'
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
        - '3000:3000'
  mongo:
    build:
      context: .
      dockerfile: Dockerfile

  
       
